// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.17.3
// source: kollect/resource/event/v1/event.proto

// Package kollect.resource.event.v1 defines event messages relating to the creation, modification and removal of
// cluster resources.

package resource

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ResourceCreatedEvent describes the creation of a cluster resource.
type ResourceCreatedEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// uid is the unique identifier for a cluster resource.
	Uid string `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	// resource is the JSON-encoded representation of the cluster resource.
	Resource []byte `protobuf:"bytes,2,opt,name=resource,proto3" json:"resource,omitempty"`
	// cluster_id is the identifier of the cluster where the resource resides.
	ClusterId string `protobuf:"bytes,3,opt,name=cluster_id,json=clusterId,proto3" json:"cluster_id,omitempty"`
}

func (x *ResourceCreatedEvent) Reset() {
	*x = ResourceCreatedEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kollect_resource_event_v1_event_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResourceCreatedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceCreatedEvent) ProtoMessage() {}

func (x *ResourceCreatedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_kollect_resource_event_v1_event_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceCreatedEvent.ProtoReflect.Descriptor instead.
func (*ResourceCreatedEvent) Descriptor() ([]byte, []int) {
	return file_kollect_resource_event_v1_event_proto_rawDescGZIP(), []int{0}
}

func (x *ResourceCreatedEvent) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *ResourceCreatedEvent) GetResource() []byte {
	if x != nil {
		return x.Resource
	}
	return nil
}

func (x *ResourceCreatedEvent) GetClusterId() string {
	if x != nil {
		return x.ClusterId
	}
	return ""
}

// ResourceDeletedEvent describes the removal of a cluster resource.
type ResourceDeletedEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// uid is the unique identifier for a cluster resource.
	Uid string `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	// cluster_id is the identifier of the cluster where the resource resides.
	ClusterId string `protobuf:"bytes,2,opt,name=cluster_id,json=clusterId,proto3" json:"cluster_id,omitempty"`
}

func (x *ResourceDeletedEvent) Reset() {
	*x = ResourceDeletedEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kollect_resource_event_v1_event_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResourceDeletedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceDeletedEvent) ProtoMessage() {}

func (x *ResourceDeletedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_kollect_resource_event_v1_event_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceDeletedEvent.ProtoReflect.Descriptor instead.
func (*ResourceDeletedEvent) Descriptor() ([]byte, []int) {
	return file_kollect_resource_event_v1_event_proto_rawDescGZIP(), []int{1}
}

func (x *ResourceDeletedEvent) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *ResourceDeletedEvent) GetClusterId() string {
	if x != nil {
		return x.ClusterId
	}
	return ""
}

// ResourceUpdatedEvent describes the modification of a cluster resource.
type ResourceUpdatedEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// uid is the unique identifier for a cluster resource.
	Uid string `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	// then is the JSON-encoded representation of the previous state of the cluster resource.
	Then []byte `protobuf:"bytes,2,opt,name=then,proto3" json:"then,omitempty"`
	// now is the JSON-encoded representation of the new state of the cluster resource.
	Now []byte `protobuf:"bytes,3,opt,name=now,proto3" json:"now,omitempty"`
	// cluster_id is the identifier of the cluster where the resource resides.
	ClusterId string `protobuf:"bytes,4,opt,name=cluster_id,json=clusterId,proto3" json:"cluster_id,omitempty"`
}

func (x *ResourceUpdatedEvent) Reset() {
	*x = ResourceUpdatedEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kollect_resource_event_v1_event_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResourceUpdatedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceUpdatedEvent) ProtoMessage() {}

func (x *ResourceUpdatedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_kollect_resource_event_v1_event_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceUpdatedEvent.ProtoReflect.Descriptor instead.
func (*ResourceUpdatedEvent) Descriptor() ([]byte, []int) {
	return file_kollect_resource_event_v1_event_proto_rawDescGZIP(), []int{2}
}

func (x *ResourceUpdatedEvent) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *ResourceUpdatedEvent) GetThen() []byte {
	if x != nil {
		return x.Then
	}
	return nil
}

func (x *ResourceUpdatedEvent) GetNow() []byte {
	if x != nil {
		return x.Now
	}
	return nil
}

func (x *ResourceUpdatedEvent) GetClusterId() string {
	if x != nil {
		return x.ClusterId
	}
	return ""
}

var File_kollect_resource_event_v1_event_proto protoreflect.FileDescriptor

var file_kollect_resource_event_v1_event_proto_rawDesc = []byte{
	0x0a, 0x25, 0x6b, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x2f, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72,
	0x63, 0x65, 0x2f, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x2f, 0x76, 0x31, 0x2f, 0x65, 0x76, 0x65, 0x6e,
	0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x19, 0x6b, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74,
	0x2e, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x2e, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x2e,
	0x76, 0x31, 0x22, 0x63, 0x0a, 0x14, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x64, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x69, 0x64, 0x12, 0x1a, 0x0a, 0x08,
	0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x08,
	0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x6c, 0x75, 0x73,
	0x74, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x63, 0x6c,
	0x75, 0x73, 0x74, 0x65, 0x72, 0x49, 0x64, 0x22, 0x47, 0x0a, 0x14, 0x52, 0x65, 0x73, 0x6f, 0x75,
	0x72, 0x63, 0x65, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x64, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12,
	0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x69,
	0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x63, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x49, 0x64,
	0x22, 0x6d, 0x0a, 0x14, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x64, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x68,
	0x65, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x74, 0x68, 0x65, 0x6e, 0x12, 0x10,
	0x0a, 0x03, 0x6e, 0x6f, 0x77, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x03, 0x6e, 0x6f, 0x77,
	0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x63, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x49, 0x64, 0x42,
	0x48, 0x5a, 0x46, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x64, 0x61,
	0x76, 0x69, 0x64, 0x73, 0x62, 0x6f, 0x6e, 0x64, 0x2f, 0x6b, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6b, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x2f, 0x72,
	0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x2f, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x2f, 0x76, 0x31,
	0x3b, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_kollect_resource_event_v1_event_proto_rawDescOnce sync.Once
	file_kollect_resource_event_v1_event_proto_rawDescData = file_kollect_resource_event_v1_event_proto_rawDesc
)

func file_kollect_resource_event_v1_event_proto_rawDescGZIP() []byte {
	file_kollect_resource_event_v1_event_proto_rawDescOnce.Do(func() {
		file_kollect_resource_event_v1_event_proto_rawDescData = protoimpl.X.CompressGZIP(file_kollect_resource_event_v1_event_proto_rawDescData)
	})
	return file_kollect_resource_event_v1_event_proto_rawDescData
}

var file_kollect_resource_event_v1_event_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_kollect_resource_event_v1_event_proto_goTypes = []interface{}{
	(*ResourceCreatedEvent)(nil), // 0: kollect.resource.event.v1.ResourceCreatedEvent
	(*ResourceDeletedEvent)(nil), // 1: kollect.resource.event.v1.ResourceDeletedEvent
	(*ResourceUpdatedEvent)(nil), // 2: kollect.resource.event.v1.ResourceUpdatedEvent
}
var file_kollect_resource_event_v1_event_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_kollect_resource_event_v1_event_proto_init() }
func file_kollect_resource_event_v1_event_proto_init() {
	if File_kollect_resource_event_v1_event_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_kollect_resource_event_v1_event_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResourceCreatedEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kollect_resource_event_v1_event_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResourceDeletedEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kollect_resource_event_v1_event_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResourceUpdatedEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_kollect_resource_event_v1_event_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_kollect_resource_event_v1_event_proto_goTypes,
		DependencyIndexes: file_kollect_resource_event_v1_event_proto_depIdxs,
		MessageInfos:      file_kollect_resource_event_v1_event_proto_msgTypes,
	}.Build()
	File_kollect_resource_event_v1_event_proto = out.File
	file_kollect_resource_event_v1_event_proto_rawDesc = nil
	file_kollect_resource_event_v1_event_proto_goTypes = nil
	file_kollect_resource_event_v1_event_proto_depIdxs = nil
}
