builds:
-
  env:
  - CGO_ENABLED=0
  mod_timestamp: "{{ .CommitTimestamp }}"
  flags:
  - -trimpath
  ldflags:
  - "-s -w -X main.version={{ .Version }} -X main.commit={{ .Commit }}"
  goos:
  - linux
  goarch:
  - amd64
  binary: "{{ .ProjectName }}"

dockers:
- id: linux_amd64
  goos: linux
  goarch: amd64
  image_templates:
  - "ghcr.io/davidsbond/kollect:{{ .Tag }}"
  - "ghcr.io/davidsbond/kollect:latest"
  dockerfile: Dockerfile
  build_flag_templates:
  - "--pull"
  - "--label=org.opencontainers.image.created={{ .Date }}"
  - "--label=org.opencontainers.image.title={{ .ProjectName }}"
  - "--label=org.opencontainers.image.revision={{ .FullCommit }}"
  - "--label=org.opencontainers.image.version={{ .Version }}"

archives:
- format: zip
  name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: "{{ .ProjectName }}_{{ .Version }}_SHA256SUMS"
  algorithm: sha256

release:
  prerelease: auto

changelog:
  use: github
