version: '3'
services:
  agent:
    build:
      context: .
    command:
      - /bin/kollect
      - --event-writer-url=kafka://kollect
      - --kube-config=/var/.kube/config
      - --cluster-id=docker-local
    environment:
      KAFKA_BROKERS: kafka:9092
    ports:
      - "8081:8081"
    volumes:
    - $HOME/.kube/config:/var/.kube/config
    restart: on-failure
    depends_on:
    - kafka

  zookeeper:
    image: wurstmeister/zookeeper

  kafka:
    image: wurstmeister/kafka
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_CREATE_TOPICS: kollect:10:1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    depends_on:
      - zookeeper
